[project]
name = "tcmembeddingmodel"
version = "0.1.0"
description = "Fine-tuning Qwen3-Embedding model for Traditional Chinese Medicine (TCM) domain"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ms-swift>=3.7.3",
]
